# Prompt Composition Rules - Single-Use Compositions for LangGraph Orchestration
# Each composition maps to a single user prompt plus system prompts

compositions:
  # OCR Compositions
  ocr_whole_document_extraction:
    description: "Extract text from entire document with OCR"
    version: "1.0.0"
    system_prompts:
      - name: "ocr_processor"
        path: "system/ocr_processor.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 80
        required: true
    user_prompts:
      - "ocr_whole_document_extraction"

  ocr_text_diagram_insight:
    description: "Extract insights from text and diagram content"
    version: "1.0.0"
    system_prompts:
      - name: "ocr_processor"
        path: "system/ocr_processor.md"
        priority: 100
        required: true
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 90
        required: true
    user_prompts:
      - "ocr_text_diagram_insight"

  layout_summarise_only:
    description: "Summarise layout and extract contract taxonomy/terms"
    version: "1.0.0"
    system_prompts: []
    user_prompts:
      - "layout_summarise"

  # Analysis Compositions
  structure_analysis_only:
    description: "Analyze contract structure from extracted text"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "contract_analysis_base"

  compliance_check_only:
    description: "Check legal compliance requirements"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "contract_analysis_base"

  financial_analysis_only:
    description: "Analyze financial terms and obligations"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "financial_analysis"

  risk_assessment_only:
    description: "Assess contract risks and potential issues"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "risk_assessment_base"

  recommendations_only:
    description: "Generate contract recommendations"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "contract_recommendations"

  # Semantic Analysis Compositions
  semantic_analysis_only:
    description: "Extract semantic meaning from diagrams"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "ocr_text_diagram_insight"

  image_semantics_only:
    description: "Analyze image semantics and content"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "ocr_text_diagram_insight"

  # Validation Compositions
  document_quality_validation_only:
    description: "Validate document quality and completeness"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
    user_prompts:
      - "validation_document_quality"

  terms_validation_only:
    description: "Validate contract terms completeness"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "validation_terms_completeness"

  final_validation_only:
    description: "Perform final output validation"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
    user_prompts:
      - "validation_final_output"

# Global composition settings (simplified)
global_settings:
  cache_ttl_seconds: 1800  # 30 minutes
  validation:
    validate_inputs: true
    validate_outputs: true

# State-specific system prompt overrides
state_overrides:
  NSW:
    system_prompt_overrides:
      australian_legal: "fragments/state_requirements/NSW/ocr_terminology.md"
  
  VIC:
    system_prompt_overrides:
      australian_legal: "fragments/state_requirements/VIC/ocr_terminology.md"
  
  QLD:
    system_prompt_overrides:
      australian_legal: "fragments/state_requirements/QLD/risk_indicators.md"