# Prompt Composition Rules - Single-Use Compositions for LangGraph Orchestration
# Each composition maps to a single user prompt plus system prompts

compositions:
  # OCR Compositions
  ocr_whole_document_extraction:
    description: "Extract text from entire document with OCR"
    version: "1.0.0"
    system_prompts:
      - name: "ocr_processor"
        path: "system/ocr_processor.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 80
        required: true
    user_prompts:
      - "ocr_whole_document_extraction"

  ocr_text_diagram_insight:
    description: "Extract insights from text and diagram content"
    version: "1.0.0"
    system_prompts:
      - name: "ocr_processor"
        path: "system/ocr_processor.md"
        priority: 100
        required: true
      # - name: "legal_specialist"
      #   path: "system/realestate_lawyer.md"
      #   priority: 90
      #   required: true
    user_prompts:
      - "ocr_text_diagram_insight"

  layout_summarise_only:
    description: "Summarise layout and extract contract taxonomy/terms"
    version: "1.0.0"
    system_prompts:
      - name: "document_core"
        path: "system/document_core.md"
        priority: 100
        required: true
    user_prompts:
      - "layout_summarise"

  # Analysis Compositions
  structure_analysis_only:
    description: "Analyze contract structure from extracted text"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "contract_analysis_base"

  contract_term_extraction:
    description: "Basic combined structure analysis using contract term extraction prompt"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "contract_term_extraction"

  contract_entities_extraction:
    description: "Extract entities from contracts using the entities extraction prompt"
    version: "1.0.0"
    system_prompts:
      - name: "entity_extraction_core"
        path: "system/entity_extraction_core.md"
        priority: 110
        required: true
    user_prompts:
      - "contract_entities_extraction"

  # Step 2 Section Analysis Compositions
  step2_parties_property:
    description: "Step 2.1 - Parties and Property Verification Analysis"
    version: "1.0.0"
    system_prompts:
      - name: "step2_section_analysis"
        path: "system/step2_section_analysis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step2_parties_property"

  step2_financial_terms:
    description: "Step 2.2 - Financial Terms Analysis and Verification"
    version: "1.0.0"
    system_prompts:
      - name: "step2_section_analysis"
        path: "system/step2_section_analysis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step2_financial_terms"

  step2_conditions:
    description: "Step 2.4 - Conditions Risk Assessment Analysis"
    version: "1.0.0"
    system_prompts:
      - name: "step2_section_analysis"
        path: "system/step2_section_analysis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step2_conditions"

  step2_warranties:
    description: "Step 2.5 - Warranties and Representations Analysis"
    version: "1.0.0"
    system_prompts:
      - name: "step2_section_analysis"
        path: "system/step2_section_analysis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step2_warranties"

  step2_default_termination:
    description: "Step 2.6 - Default and Termination Analysis"
    version: "1.0.0"
    system_prompts:
      - name: "step2_section_analysis"
        path: "system/step2_section_analysis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step2_default_termination"

  step2_diagram_semantics:
    description: "Step 2.3 - Diagram/Image Semantics Analysis"
    version: "1.0.0"
    system_prompts:
      - name: "step2_image_semantics"
        path: "system/step2_image_semantics.md"
        priority: 105
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "image_semantics"

  # Step 3 Synthesis Compositions
  step3_risk_aggregation:
    description: "Step 3 - Risk Aggregation and Prioritization"
    version: "1.0.0"
    system_prompts:
      - name: "step3_synthesis_system"
        path: "system/step3_synthesis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step3_risk_aggregation"

  step3_action_plan:
    description: "Step 3 - Recommended Actions & Timeline"
    version: "1.0.0"
    system_prompts:
      - name: "step3_synthesis_system"
        path: "system/step3_synthesis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step3_action_plan"

  step3_compliance_score:
    description: "Step 3 - Compliance Readiness Score"
    version: "1.0.0"
    system_prompts:
      - name: "step3_synthesis_system"
        path: "system/step3_synthesis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step3_compliance_score"

  step3_buyer_report:
    description: "Step 3 - Buyer Report Synthesis"
    version: "1.0.0"
    system_prompts:
      - name: "step3_synthesis_system"
        path: "system/step3_synthesis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step3_buyer_report"

  step2_settlement:
    description: "Step 2.7 - Settlement Logistics Analysis"
    version: "1.0.0"
    system_prompts:
      - name: "step2_section_analysis"
        path: "system/step2_section_analysis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step2_settlement"

  step2_title_encumbrances:
    description: "Step 2.8 - Title and Encumbrances Analysis with Diagram Integration"
    version: "1.0.0"
    system_prompts:
      - name: "step2_section_analysis"
        path: "system/step2_section_analysis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step2_title_encumbrances"

  step2_adjustments:
    description: "Step 2.9 - Adjustments and Outgoings Calculator"
    version: "1.0.0"
    system_prompts:
      - name: "step2_section_analysis"
        path: "system/step2_section_analysis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step2_adjustments"

  step2_disclosure:
    description: "Step 2.10 - Disclosure Compliance Check"
    version: "1.0.0"
    system_prompts:
      - name: "step2_section_analysis"
        path: "system/step2_section_analysis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step2_disclosure"

  step2_special_risks:
    description: "Step 2.11 - Special Risks Identification"
    version: "1.0.0"
    system_prompts:
      - name: "step2_section_analysis"
        path: "system/step2_section_analysis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step2_special_risks"

  step2_cross_validation:
    description: "Step 2.12 - Cross-Section Validation and Consistency Checks"
    version: "1.0.0"
    system_prompts:
      - name: "step2_section_analysis"
        path: "system/step2_section_analysis.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "step2_cross_validation"

  compliance_check_only:
    description: "Check legal compliance requirements"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "contract_analysis_base"

  financial_analysis_only:
    description: "Analyze financial terms and obligations"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "financial_analysis"

  risk_assessment_only:
    description: "Assess contract risks and potential issues"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "risk_assessment_base"

  recommendations_only:
    description: "Generate contract recommendations"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "contract_recommendations"

  # Semantic Analysis Compositions
  semantic_analysis_only:
    description: "Extract semantic meaning from diagrams"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "ocr_text_diagram_insight"

  image_semantics_only:
    description: "Analyze image semantics and content"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "ocr_text_diagram_insight"

  # Validation Compositions
  document_quality_validation_only:
    description: "Validate document quality and completeness"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
    user_prompts:
      - "validation_document_quality"

  terms_validation_only:
    description: "Validate contract terms completeness"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
      - name: "australian_legal"
        path: "system/conveyancer.md"
        priority: 90
        required: true
    user_prompts:
      - "validation_terms_completeness"

  final_validation_only:
    description: "Perform final output validation"
    version: "1.0.0"
    system_prompts:
      - name: "legal_specialist"
        path: "system/realestate_lawyer.md"
        priority: 100
        required: true
    user_prompts:
      - "validation_final_output"

# Global composition settings (simplified)
global_settings:
  cache_ttl_seconds: 1800  # 30 minutes
  validation:
    validate_inputs: true
    validate_outputs: true

# State-specific system prompt overrides
state_overrides:
  NSW:
    system_prompt_overrides:
      australian_legal: "fragments/state_requirements/NSW/ocr_terminology.md"
  
  VIC:
    system_prompt_overrides:
      australian_legal: "fragments/state_requirements/VIC/ocr_terminology.md"
  
  QLD:
    system_prompt_overrides:
      australian_legal: "fragments/state_requirements/QLD/risk_indicators.md"