# Central registry of all prompts with metadata and organization

registry:
  system_prompts:
    assistant_core:
      path: "system/base/assistant_core.md"
      category: "base"
      priority: 100
      dependencies: []
      description: "Core AI assistant behavior and personality"
      required_for: ["contract_analysis_complete", "ocr_extraction_specialized"]
      
    safety_guidelines:
      path: "system/base/safety_guidelines.md"
      category: "base"
      priority: 95
      dependencies: ["assistant_core"]
      description: "Safety and ethical guidelines for AI responses"
      
    reasoning_framework:
      path: "system/base/reasoning_framework.md"
      category: "base"
      priority: 90
      dependencies: ["assistant_core"]
      description: "Logical reasoning and analysis framework"
      
    legal_specialist:
      path: "system/domain/legal_specialist.md"
      category: "domain"
      priority: 80
      dependencies: ["assistant_core", "reasoning_framework"]
      description: "Legal domain expertise and analysis capabilities"
      required_for: ["contract_analysis_complete", "risk_assessment_comprehensive"]
      
    contract_analyst:
      path: "system/domain/contract_analyst.md"
      category: "domain"
      priority: 75
      dependencies: ["legal_specialist"]
      description: "Specialized contract analysis expertise"
      
    ocr_processor:
      path: "system/domain/ocr_processor.md"
      category: "domain"
      priority: 70
      dependencies: ["assistant_core"]
      description: "OCR processing and document extraction behavior"
      required_for: ["ocr_extraction_specialized"]
      
    risk_analyst:
      path: "system/domain/risk_analyst.md"
      category: "domain"
      priority: 75
      dependencies: ["legal_specialist", "reasoning_framework"]
      description: "Risk assessment and analysis expertise"
      
    workflow_coordinator:
      path: "system/domain/workflow_coordinator.md"
      category: "domain"
      priority: 65
      dependencies: ["assistant_core"]
      description: "Multi-step workflow coordination and user guidance"
      
    australian_legal:
      path: "system/context/australian_legal.md"
      category: "context"
      priority: 85
      dependencies: ["legal_specialist"]
      description: "Australian legal system context and terminology"
      required_for: ["contract_analysis_complete", "risk_assessment_comprehensive"]
      
    state_context:
      path: "system/context/state_specific/dynamic_state.md"
      category: "context"
      priority: 60
      dependencies: ["australian_legal"]
      description: "Dynamic state-specific legal context (resolved at runtime)"
      
    # State-specific contexts
    nsw_context:
      path: "system/context/state_specific/nsw_context.md"
      category: "context"
      priority: 60
      dependencies: ["australian_legal"]
      description: "NSW-specific legal context and requirements"
      
    vic_context:
      path: "system/context/state_specific/vic_context.md"
      category: "context"
      priority: 60
      dependencies: ["australian_legal"]
      description: "Victoria-specific legal context and requirements"
      
    qld_context:
      path: "system/context/state_specific/qld_context.md"
      category: "context"
      priority: 60
      dependencies: ["australian_legal"]
      description: "Queensland-specific legal context and requirements"

  user_prompts:
    contract_analysis_base:
      path: "user/instructions/contract_analysis_base.md"
      category: "instructions"
      system_requirements: ["legal_specialist", "australian_legal"]
      description: "Fragment-based comprehensive contract analysis instructions"
      estimated_tokens: 8000
      
    ocr_extraction_base:
      path: "user/instructions/ocr_extraction_base.md"
      category: "instructions"
      system_requirements: ["ocr_processor"]
      description: "Fragment-based OCR extraction and document processing instructions"
      estimated_tokens: 4000
      
    risk_assessment_base:
      path: "user/instructions/risk_assessment_base.md"
      category: "instructions"
      system_requirements: ["legal_specialist", "australian_legal"]
      description: "Fragment-based risk assessment and evaluation instructions"
      estimated_tokens: 8000
      
    financial_analysis:
      path: "user/instructions/financial_analysis.md"
      category: "instructions"
      system_requirements: ["legal_specialist", "risk_analyst"]
      description: "Financial terms and obligations analysis"
      estimated_tokens: 5000
      
    quick_analysis:
      path: "user/instructions/quick_analysis.md"
      category: "instructions"
      system_requirements: ["legal_specialist"]
      description: "Fast contract analysis for basic checks"
      estimated_tokens: 3000
      
    contract_workflow:
      path: "user/workflow/contract_workflow.md"
      category: "workflows"
      system_requirements: ["legal_specialist", "workflow_coordinator"]
      description: "Multi-step contract analysis workflow"
      estimated_tokens: 10000
      
    validation_workflow:
      path: "user/validation/document_quality_validation.md"
      category: "workflows"
      system_requirements: ["assistant_core"]
      description: "Validation and quality assurance workflow"
      estimated_tokens: 2000

    # Validation templates
    validation_document_quality:
      path: "user/validation/document_quality_validation.md"
      category: "validation"
      system_requirements: ["assistant_core", "legal_specialist"]
      description: "Document quality validation template"
      estimated_tokens: 3000

    validation_final_output:
      path: "user/validation/final_output_validation.md"
      category: "validation" 
      system_requirements: ["assistant_core", "legal_specialist"]
      description: "Final output validation template"
      estimated_tokens: 2500

    validation_terms_completeness:
      path: "user/validation/terms_completeness_validation.md"
      category: "validation"
      system_requirements: ["assistant_core", "legal_specialist"]
      description: "Contract terms completeness validation template"
      estimated_tokens: 2000
      
    # clarification_prompts:
    #   path: "interactions/clarification.md"
    #   category: "interactions"
    #   description: "User clarification and follow-up prompts"
    #   estimated_tokens: 1000
      
    state_specific_instructions:
      path: "user/instructions/state_specific_analysis.md"
      category: "instructions"
      system_requirements: ["legal_specialist", "australian_legal"]
      description: "State-specific analysis instructions"
      estimated_tokens: 4000

    # OCR User Prompts
    ocr_text_diagram_insight:
      path: "user/ocr/text_diagram_insight.md"
      category: "ocr"
      system_requirements: ["ocr_processor", "legal_specialist"]
      description: "Extract insights from text and diagram content in documents"
      estimated_tokens: 3000

    ocr_whole_document_extraction:
      path: "user/ocr/whole_document_extraction.md"
      category: "ocr"
      system_requirements: ["ocr_processor", "legal_specialist"]
      description: "Extract text from entire document with OCR"
      estimated_tokens: 4000

    ocr_general_document_extraction:
      path: "user/ocr/general_document_extraction.md"
      category: "ocr"
      system_requirements: ["ocr_processor"]
      description: "General document text extraction and processing"
      estimated_tokens: 3000

    ocr_extraction:
      path: "user/ocr/ocr_extraction.md"
      category: "ocr"
      system_requirements: ["ocr_processor"]
      description: "Standard OCR text extraction template"
      estimated_tokens: 2500

  shared_components:
    legal_terms:
      path: "shared/fragments/legal_terms.md"
      type: "fragment"
      reusable: true
      description: "Common Australian legal terminology definitions"
      
    formatting_rules:
      path: "shared/fragments/formatting_rules.md"
      type: "fragment"
      reusable: true
      description: "Output formatting standards and guidelines"
      
    validation_rules:
      path: "shared/fragments/validation_rules.md"
      type: "fragment"
      reusable: true
      description: "Input validation patterns and requirements"
      
    currency_formatting:
      path: "shared/macros/currency_formatting.md"
      type: "macro"
      reusable: true
      description: "Jinja2 macros for currency formatting"
      
    date_formatting:
      path: "shared/macros/date_formatting.md"
      type: "macro"
      reusable: true
      description: "Jinja2 macros for date formatting"


# Composition compatibility matrix
compatibility:
  model_requirements:
    gemini-2.5-flash:
      max_tokens: 32000
      supports_system_prompts: true
      optimal_temperature: [0.1, 0.4]
      
    gpt-4:
      max_tokens: 8000
      supports_system_prompts: true
      optimal_temperature: [0.0, 0.3]
      
    claude-3-opus:
      max_tokens: 16000
      supports_system_prompts: true
      optimal_temperature: [0.0, 0.5]

# Quality metrics and monitoring
quality_metrics:
  token_usage:
    target_efficiency: 0.85  # Tokens used / Total available
    max_composition_tokens: 24000
    warn_threshold: 0.90
    
  composition_complexity:
    max_system_prompts: 6
    max_user_prompts: 4
    max_nesting_depth: 3
    
  performance_targets:
    composition_time_ms: 500
    cache_hit_rate: 0.80
    validation_success_rate: 0.95