# Risk Assessment Fragment Orchestration Configuration

prompt_id: "risk_assessment"
description: "Orchestrates state-specific risk assessment fragments for property contracts"
base_template: "user/instructions/risk_assessment_base.md"

fragments:
  # State-specific risk indicators
  state_specific:
    condition: "australian_state"
    composition: "replace"
    priority: 80
    mappings:
      NSW:
        - "fragments/nsw/risk_indicators.md"
      VIC:
        - "fragments/vic/risk_indicators.md"
      QLD:
        - "fragments/qld/risk_indicators.md"
      SA:
        - "fragments/sa/risk_indicators.md"
      WA:
        - "fragments/wa/risk_indicators.md"
  
  # Financial risk assessment (always included)
  financial_risk:
    always_include:
      - "fragments/common/financial_risk_indicators.md"
    priority: 85
  
  # User experience level guidance
  experience_level:
    condition: "user_experience"
    composition: "replace"
    priority: 70
    mappings:
      novice:
        - "fragments/guidance/first_time_buyer_risks.md"
        - "fragments/guidance/beginner_risk_concepts.md"
      experienced:
        - "fragments/guidance/experienced_buyer_risks.md"
        - "fragments/guidance/advanced_risk_factors.md"
      expert:
        - "fragments/guidance/sophisticated_risk_analysis.md"
        - "fragments/guidance/commercial_risk_factors.md"
  
  # Contract type specific risks
  contract_type_specific:
    condition: "contract_type"
    composition: "union"
    priority: 75
    mappings:
      PURCHASE_AGREEMENT:
        - "fragments/purchase/purchase_risk_factors.md"
      LEASE_AGREEMENT:
        - "fragments/lease/lease_risk_factors.md"
      OPTION_AGREEMENT:
        - "fragments/option/option_risk_factors.md"
  
  # Investment purpose specific considerations
  investment_focus:
    condition: "investment_purpose"
    composition: "union"
    priority: 60
    mappings:
      residential_investment:
        - "fragments/investment/rental_property_risks.md"
      commercial_investment:
        - "fragments/investment/commercial_property_risks.md"
      development:
        - "fragments/investment/development_risks.md"
      owner_occupier:
        - "fragments/investment/owner_occupier_considerations.md"

# Quality and performance settings
quality_settings:
  validation:
    require_all_fragments: false
    fallback_on_missing: true
    log_missing_fragments: true
  
  performance:
    cache_resolved_fragments: true
    cache_ttl_seconds: 1800  # 30 minutes
    max_fragment_size_kb: 50
    warn_on_large_fragments: true

# Conditional logic for complex risk scenarios
conditional_rules:
  # High value transactions
  high_value_transaction:
    condition: "transaction_value > 2000000"
    action: "include_additional_risk_analysis"
    fragments:
      - "fragments/high_value/sophisticated_risk_factors.md"
      - "fragments/high_value/tax_implications.md"
  
  # Foreign buyer considerations
  foreign_buyer:
    condition: "buyer_type == 'foreign'"
    action: "include_foreign_buyer_risks"
    fragments:
      - "fragments/foreign_buyer/firb_compliance.md"
      - "fragments/foreign_buyer/additional_duties.md"
  
  # Strata/body corporate properties
  strata_property:
    condition: "property_type == 'strata' || property_type == 'unit'"
    action: "include_strata_risks"
    fragments:
      - "fragments/strata/body_corporate_risks.md"
      - "fragments/strata/strata_title_complications.md"

# Metadata for orchestration
metadata:
  version: "1.0.0"
  last_updated: "2024-01-15"
  author: "Legal Technology Team"
  review_frequency: "quarterly"
  
  dependencies:
    - "legal_terms_glossary"
    - "state_legislation_updates"
    - "market_risk_indicators"
  
  metrics:
    track_fragment_usage: true
    measure_risk_assessment_accuracy: true
    monitor_user_feedback: true